### ISSUE TITLE
Access token required

### ISSUE THREAD

**Issue by GewoonJaap** [kevinta893/unity3d-travis-ci#2] opened 2019-01-19 14:27 UTC
```
/Users/travis/.rvm/gems/ruby-2.4.2/gems/octokit-4.6.2/lib/octokit/client/authorizations.rb:125:in `scopes': Access token required (ArgumentError)
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-releases-1.10.6/lib/dpl/provider/releases.rb:89:in `check_auth'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-1.10.6/lib/dpl/provider.rb:187:in `block in deploy'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-1.10.6/lib/dpl/cli.rb:41:in `fold'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-1.10.6/lib/dpl/provider.rb:186:in `deploy'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-1.10.6/lib/dpl/cli.rb:32:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-1.10.6/lib/dpl/cli.rb:7:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.2/gems/dpl-1.10.6/bin/dpl:5:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/dpl:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.4.2/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by kevinta893** [comment] 2019-01-20 11:56
Hi, I'm not sure what the issue is here. What version of Unity are you using? Where is this error happening? Can I get a complete log?

**Comment by GewoonJaap** [comment] 2019-01-20 12:18
Already fixed. But how to export the game .exe and not the unity package?

Op zo 20 jan. 2019 12:56 schreef kevinta893 <notifications@github.com:

**Comment by kevinta893** [comment] 2019-01-20 12:40
Since this is no longer an issue then I will close this issue for now.

To export a game as .exe on Travis, please take a look at the **travis-build/build.sh** script. Here you will find an example command to build a Unity game to target the Windows 64-bit player. You can also see this happen on the travis build logs. Then replace the command in **travis-build/export-unity-package.sh**.

If you need other build options, please look at the Unity manual: https://docs.unity3d.com/Manual/CommandLineArguments.html

If you want to target other build platforms like Android and IOS, please make sure you install the necessary *Build Target Support* packages.

I recommend testing your builds in the command-line locally on your computer to get the right export command-line parameters/flags. You also may need to change the *export-unity-package.sh* to ensure that the .exe and related data files are also included too.

**Closed as completed by kevinta893** 2019-01-20 12:40 UTC
